# Generated by Django 5.2.8 on 2025-11-24 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(blank=True, max_length=255, null=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='tracks/')),
                ('artwork', models.ImageField(blank=True, null=True, upload_to='tracks/artwork/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='playlists/artwork/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tracks', models.ManyToManyField(blank=True, related_name='playlists', to='music.track')),
            ],
        ),
    ]
